const surahOptions = [
  { value: 1, label: 'Al-Fatihah', verses: 7 },
  { value: 2, label: 'Al-Baqarah', verses: 286 },
  { value: 3, label: 'Ali `Imran', verses: 200 },
  { value: 4, label: 'An-Nisa', verses: 176 },
  { value: 5, label: 'Al-Ma`idah', verses: 120 },
  { value: 6, label: 'Al-An`am', verses: 165 },
  { value: 7, label: 'Al-A`raf', verses: 206 },
  { value: 8, label: 'Al-Anfal', verses: 75 },
  { value: 9, label: 'At-Taubah', verses: 129 },
  { value: 10, label: 'Yunus', verses: 109 },
  { value: 11, label: 'Hud', verses: 123 },
  { value: 12, label: 'Yusuf', verses: 111 },
  { value: 13, label: 'Ar-Ra`d', verses: 43 },
  { value: 14, label: 'Ibrahim', verses: 52 },
  { value: 15, label: 'Al-Hijr', verses: 99 },
  { value: 16, label: 'An-Nahl', verses: 128 },
  { value: 17, label: 'Al-Isra', verses: 111 },
  { value: 18, label: 'Al-Kahf', verses: 110 },
  { value: 19, label: 'Maryam', verses: 98 },
  { value: 20, label: 'Ta-Ha', verses: 135 },
  { value: 21, label: 'Al-Anbiya', verses: 112 },
  { value: 22, label: 'Al-Hajj', verses: 78 },
  { value: 23, label: 'Al-Mu`minun', verses: 118 },
  { value: 24, label: 'An-Nur', verses: 64 },
  { value: 25, label: 'Al-Furqan', verses: 77 },
  { value: 26, label: 'Ash-Shu`ara', verses: 227 },
  { value: 27, label: 'An-Naml', verses: 93 },
  { value: 28, label: 'Al-Qasas', verses: 88 },
  { value: 29, label: 'Al-`Ankabut', verses: 69 },
  { value: 30, label: 'Ar-Rum', verses: 60 },
  { value: 31, label: 'Luqman', verses: 34 },
  { value: 32, label: 'As-Sajdah', verses: 30 },
  { value: 33, label: 'Al-Ahzab', verses: 73 },
  { value: 34, label: 'Saba', verses: 54 },
  { value: 35, label: 'Fatir', verses: 45 },
  { value: 36, label: 'Ya-Sin', verses: 83 },
  { value: 37, label: 'As-Saffat', verses: 182 },
  { value: 38, label: 'Sad', verses: 88 },
  { value: 39, label: 'Az-Zumar', verses: 75 },
  { value: 40, label: 'Ghafir', verses: 85 },
  { value: 41, label: 'Fussilat', verses: 54 },
  { value: 42, label: 'Ash-Shura', verses: 53 },
  { value: 43, label: 'Az-Zukhruf', verses: 89 },
  { value: 44, label: 'Ad-Dukhan', verses: 59 },
  { value: 45, label: 'Al-Jathiya', verses: 37 },
  { value: 46, label: 'Al-Ahqaf', verses: 35 },
  { value: 47, label: 'Muhammad', verses: 38 },
  { value: 48, label: 'Al-Fath', verses: 29 },
  { value: 49, label: 'Al-Hujurat', verses: 18 },
  { value: 50, label: 'Qaf', verses: 45 },
  { value: 51, label: 'Adh-Dhariyat', verses: 60 },
  { value: 52, label: 'At-Tur', verses: 49 },
  { value: 53, label: 'An-Najm', verses: 62 },
  { value: 54, label: 'Al-Qamar', verses: 55 },
  { value: 55, label: 'Ar-Rahman', verses: 78 },
  { value: 56, label: 'Al-Waqi`ah', verses: 96 },
  { value: 57, label: 'Al-Hadid', verses: 29 },
  { value: 58, label: 'Al-Mujadilah', verses: 22 },
  { value: 59, label: 'Al-Hashr', verses: 24 },
  { value: 60, label: 'Al-Mumtahanah', verses: 13 },
  { value: 61, label: 'As-Saff', verses: 14 },
  { value: 62, label: 'Al-Jumu`ah', verses: 11 },
  { value: 63, label: 'Al-Munafiqun', verses: 11 },
  { value: 64, label: 'At-Taghabun', verses: 18 },
  { value: 65, label: 'At-Talaq', verses: 12 },
  { value: 66, label: 'At-Tahrim', verses: 12 },
  { value: 67, label: 'Al-Mulk', verses: 30 },
  { value: 68, label: 'Al-Qalam', verses: 52 },
  { value: 69, label: 'Al-Haqqah', verses: 52 },
  { value: 70, label: 'Al-Ma`arij', verses: 44 },
  { value: 71, label: 'Nuh', verses: 28 },
  { value: 72, label: 'Al-Jinn', verses: 28 },
  { value: 73, label: 'Al-Muzzammil', verses: 20 },
  { value: 74, label: 'Al-Muddaththir', verses: 56 },
  { value: 75, label: 'Al-Qiyamah', verses: 40 },
  { value: 76, label: 'Al-Insan', verses: 31 },
  { value: 77, label: 'Al-Mursalat', verses: 50 },
  { value: 78, label: 'An-Naba', verses: 40 },
  { value: 79, label: 'An-Nazi`at', verses: 46 },
  { value: 80, label: '`Abasa', verses: 42 },
  { value: 81, label: 'At-Takwir', verses: 29 },
  { value: 82, label: 'Al-Infitar', verses: 19 },
  { value: 83, label: 'Al-Mutaffifin', verses: 36 },
  { value: 84, label: 'Al-Inshiqaq', verses: 25 },
  { value: 85, label: 'Al-Buruj', verses: 22 },
  { value: 86, label: 'At-Tariq', verses: 17 },
  { value: 87, label: 'Al-A`la', verses: 19 },
  { value: 88, label: 'Al-Ghashiyah', verses: 26 },
  { value: 89, label: 'Al-Fajr', verses: 30 },
  { value: 90, label: 'Al-Balad', verses: 20 },
  { value: 91, label: 'Ash-Shams', verses: 15 },
  { value: 92, label: 'Al-Lail', verses: 21 },
  { value: 93, label: 'Ad-Duha', verses: 11 },
  { value: 94, label: 'Ash-Sharh', verses: 8 },
  { value: 95, label: 'At-Tin', verses: 8 },
  { value: 96, label: 'Al-Alaq', verses: 19 },
  { value: 97, label: 'Al-Qadr', verses: 5 },
  { value: 98, label: 'Al-Bayyinah', verses: 8 },
  { value: 99, label: 'Az-Zalzalah', verses: 8 },
  { value: 100, label: 'Al-`Adiyat', verses: 11 },
  { value: 101, label: 'Al-Qari`ah', verses: 11 },
  { value: 102, label: 'At-Takathur', verses: 8 },
  { value: 103, label: 'Al-`Asr', verses: 3 },
  { value: 104, label: 'Al-Humazah', verses: 9 },
  { value: 105, label: 'Al-Fil', verses: 5 },
  { value: 106, label: 'Quraysh', verses: 4 },
  { value: 107, label: 'Al-Ma`un', verses: 7 },
  { value: 108, label: 'Al-Kauthar', verses: 3 },
  { value: 109, label: 'Al-Kafirun', verses: 6 },
  { value: 110, label: 'An-Nasr', verses: 3 },
  { value: 111, label: 'Al-Masad', verses: 5 },
  { value: 112, label: 'Al-Ikhlas', verses: 4 },
  { value: 113, label: 'Al-Falaq', verses: 5 },
  { value: 114, label: 'An-Nas', verses: 6 },
]

const tafsirOptions = [
  {
    value: 'en-tafisr-ibn-kathir',
    label: 'Tafsir Ibn Kathir (English) ',
    lang: 'en',
  },
  {
    value: 'ar-tafsir-ibn-kathir',
    label: 'Tafsir Ibn Kathir (العربية) ',
    lang: 'ar',
  },
  {
    value: 'tafseer-ibn-e-kaseer-urdu',
    label: 'Tafsir Ibn Kathir (اردو) ',
    lang: 'ur',
  },
  {
    value: 'en-tafsir-maarif-ul-quran',
    label: 'Tafsir Maarif ul Quran (English) ',
    lang: 'en',
  },
  {
    value: 'tafsir-bayan-ul-quran',
    label: 'Tafsir Bayan ul Quran (اردو) ',
    lang: 'ur',
  },
  {
    value: 'tazkiru-quran-ur',
    label: 'Tazkirul Quran (اردو) ',
    lang: 'ur',
  },
  {
    value: 'tazkirul-quran-en',
    label: 'Tazkirul Quran (English) ',
    lang: 'en',
  },
  {
    value: 'ar-tafsir-al-tabari',
    label: 'Tafsir Al-Tabari (العربية) ',
    lang: 'ar',
  },
  {
    value: 'ar-tafsir-muyassar',
    label: 'Tafsir Muyassar (العربية) ',
    lang: 'ar',
  },
  {
    value: 'ar-tafseer-al-qurtubi',
    label: 'Tafsir Al-Qurtubi (العربية) ',
    lang: 'ar',
  },
  {
    value: 'ar-tafsir-al-baghawi',
    label: 'Tafsir Al-Baghawi (العربية) ',
    lang: 'ar',
  },
  {
    value: 'ar-tafseer-al-saddi',
    label: 'Tafsir Al-Saddi (العربية) ',
    lang: 'ar',
  },
  {
    value: 'ar-tafsir-al-wasit',
    label: 'Tafsir Al-Wasit (العربية) ',
    lang: 'ar',
  },
]

const translationOptions = [
  {
    label: 'Saheeh International (English)',
    value: 20,
  },
  {
    label: 'Mufti Taqi Usmani (English)',
    value: 84,
  },
  {
    label: 'Muhammad Sarwar (English)',
    value: 85,
  },
  // {
  //   label: 'Mohsin Khan (English)',
  //   value: 21,
  // },
  {
    label: 'Pickthall (English)',
    value: 22,
  },
  // {
  //   label: 'Fatatih Muhammad Jallandhari (اردو)',
  //   value: 19,
  // },
  // {
  //   label: 'Muhammad Junagarhi (اردو)',
  //   value: 18,
  // },
  // {
  //   label: 'Shaykh al Hind Maulana Mahmood Hasan (اردو)',
  //   value: 17,
  // },
]

export const quranExplorerData = {
  surahOptions,
  tafsirOptions,
  translationOptions,
}
