// This file was generated by RedwoodJS
import FatalErrorPageType from '/Users/hossamsulleman/Documents/GitHub/islamic-ware/mail/web/src/pages/FatalErrorPage/FatalErrorPage'
import NotFoundPageType from '/Users/hossamsulleman/Documents/GitHub/islamic-ware/mail/web/src/pages/NotFoundPage/NotFoundPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const NotFoundPage: typeof NotFoundPageType
}
